#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use Getopt::Long qw(GetOptions :config no_auto_abbrev no_ignore_case);

GetOptions(
	'daemon|d' => sub { $ENV{VELICIO_DAEMON} = 1 },
	'help|?' => \my $help,
	'http|h=s' => sub { $ENV{VELICIO_HTTP_SERVER} = $_[1] },
	'websocket|w=s' => sub { $ENV{VELICIO_WEBSOCKET_SERVER} = $_[1] },
	'log-level|l=s' => sub { $ENV{VELICIO_LOG_LEVEL} = $_[1] },
	'no-demo-mode|D' => sub { $ENV{VELICIO_DEMO_MODE} = 0 },
	'ping-interval=i' => sub { $ENV{VELICIO_PING_INTERVAL} = $_[1] },
	'check-interval=i' => sub { $ENV{VELICIO_CHECK_INTERVAL} = $_[1] },
	'inactivity-timeout=i' => sub { $ENV{VELICIO_INACTIVITY_TIMEOUT} = $_[1] },
	'connection-attempts=i' => sub { $ENV{VELICIO_CONNECTION_ATTEMPTS} = $_[1] },
);

# Usage
die <<"EOF" if $help;
usage: $0 [OPTIONS]

  velicio -h https://velicio.us
  velicio -w wss://velicio.us

These options are available:
  -d, --daemon              Run as a daemon
  -?, --help                Show this message.
  -h, --http                Set server for HTTP requests
  -w, --websocket           Set server for Websocket conversations
  -l, --log-level           Set the log level, defaults to ERROR
  -D, --no-demo-mode        Turn off demo mode
      --ping-interval       Set the ping interval
      --check-interval      Set the check interval
      --inactivity-timeout  Set the inactivity timeout
      --connection-attempts Set the inactivity timeout
      stop                  Stop daemon gracefully.
      status                Show daemon status
EOF

use Velicio;

my $velicio = new Velicio or die "Options: [-d] [-h http://server] [-w ws://server]\n";

if ( 0 ) {
	# TODO: Send email to link a user to this agent
	# TODO: Send any valid run hash
	# TODO: Get status
	if ( 0 ) {
		$velicio->post;
	}
	exit;
}

$velicio->websocket;

=head1 NAME

velicio - Agent for Velicious server

=head1 SYNOPSIS

  $ velicio --help
  $ velicio -h https://velicio.us
  $ velicio -w wss://velicio.us

=head1 DESCRIPTION

Start L<velicio> agent with the L<Velicio> agent library.

=head1 SEE ALSO

L<Velicio>, L<http://velicio.us>.

=cut
